// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDH342FtaA-uYwIO2EoED-i919fkSE2Ug',
    appId: '1:322237605855:web:4239084873668ce5f4866a',
    messagingSenderId: '322237605855',
    projectId: 'proyectofinal-568f2',
    authDomain: 'proyectofinal-568f2.firebaseapp.com',
    storageBucket: 'proyectofinal-568f2.firebasestorage.app',
    measurementId: 'G-CDL8FG60G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOS5LWk1GxBlA3INA_9UeRg-IE0IkK1eQ',
    appId: '1:322237605855:android:9aa8e5ee43470886f4866a',
    messagingSenderId: '322237605855',
    projectId: 'proyectofinal-568f2',
    storageBucket: 'proyectofinal-568f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm_KihIPtYCHaaxMGSAsHaku7V3eYTgUQ',
    appId: '1:322237605855:ios:73390d255a9c221cf4866a',
    messagingSenderId: '322237605855',
    projectId: 'proyectofinal-568f2',
    storageBucket: 'proyectofinal-568f2.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm_KihIPtYCHaaxMGSAsHaku7V3eYTgUQ',
    appId: '1:322237605855:ios:73390d255a9c221cf4866a',
    messagingSenderId: '322237605855',
    projectId: 'proyectofinal-568f2',
    storageBucket: 'proyectofinal-568f2.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDH342FtaA-uYwIO2EoED-i919fkSE2Ug',
    appId: '1:322237605855:web:3250904932946b01f4866a',
    messagingSenderId: '322237605855',
    projectId: 'proyectofinal-568f2',
    authDomain: 'proyectofinal-568f2.firebaseapp.com',
    storageBucket: 'proyectofinal-568f2.firebasestorage.app',
    measurementId: 'G-BZH4ZBN0W0',
  );
}
